Images from backend
BKSalman/musawarah pull request #68
Opened 2024-02-11 19:36 UTC by BKSalman

Instead of using R2 URL directly, add an endpoint to get the images for better control on access

2024-02-13 11:27 UTC, mohad12211 requested changes
General review, will test when i get home

2024-02-13 11:27 UTC, mohad12211 commented on src/s3/routes.rs
> +        ImagesError::BadRequest
This can be 500 (Internal Server Error) if the request fails or 400 (Bad Request) if the path is invalid, maybe add a TODO to differentiate between the two

2024-02-13 11:27 UTC, mohad12211 commented on src/s3/routes.rs
> +    Ok(bytes.to_vec())
Does this do an extra allocation?

2024-02-25 19:05 UTC, BKSalman commented on src/s3/routes.rs
> +        ImagesError::BadRequest
just handled it in last commit

2024-02-25 19:05 UTC, BKSalman commented on src/s3/routes.rs
> +    Ok(bytes.to_vec())
removed the `to_vec`

2024-02-26 15:54 UTC, mohad12211 approved these changes

2024-02-26 19:44 UTC, merged